### ISSUE TITLE
Salesforce returns "Success" without records being created.

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#48] opened 2016-04-07 13:47 UTC
I am looking in Salesforce, and I don't see new records that were submitted today, although the bridge says the submissions are successful. When I try to reprocess, they say they are still successful. If they were actually being inserted the submissions would fail due to duplicate meta instance IDs. Has Livelyhoods been put on hold due to their high levels of submissions?

**Comment by ryanwongsa** [comment] 2016-04-11 12:10
Same here. Did you perhaps use the combine function as on 6 April there was no problem but now trying the same functions again, they show to be submitted yet are not in Salesforce.

**Comment by taylordowns2000** [comment] 2016-04-11 12:15
@ryanwongsa , thanks to @Natalieflp we've confirmed that by nesting certain functions in a job you can get Salesforce to return a 200, though no records are created. @Natalieflp , was your original job using the `combine` helper function?

In the meantime I have an example of a job that creates child records, linked to parents, without using "combine":

```js
each(
    dataPath("data[*]"),
    create("ODK__c", fields(
        field("Transaction_Date__c", dataValue("today")),
        field("Person_Responsible__c", dataValue("person")),
        field("Issue__c", dataValue("issue")),
        field("Issue_Description__c", dataValue("issue_description")),
        field("metainstanceid__c", dataValue("*meta-instance-id*"))
    ))
),
each(
    merge(dataPath("scan_products[*]"), fields(
        field("end", dataValue("end")),
        field("parentId", lastReferenceValue("id"))
        )),
    create("ODK_Child_1__c", fields(
        field("ODK__c", dataValue("parentId")),
        field("Barcode__c", dataValue("product_barcode")),
        field("ODK_Form_Completed__c", dataValue("end"))
    ))
)
```

**Comment by taylordowns2000** [comment] 2016-04-11 19:04
@ryanwongsa , @Natalieflp , we reviewed the functionality of the `each(...)` and `combine(...)` functions today and realized that we should have them return the same data they were given, rather than the data from inside the array they accessed. You can use the new `beta.each(...)` function right now, and we'll release a `beta.combine(...) function tomorrow. In later releases of OpenFn you'll be able to specify a version number with your job to ensure compatibility with whichever version of the helper you're using, if any.

I'm hoping this might also help with your `combine(...)` issues! Have pasted an expression that dives in and out of repeat blocks in ODK below for you reference:
```js
beta.each(
  "$.data.data[*]",
  create("ODK__c", fields(
      field("Event_Type__c", dataValue("event_type")),
      field("Training_Type__c", dataValue("training_type")),
      field("Event_Leader_ID__c", dataValue("leader")),
      field("Event_Date__c", dataValue("date")),
      field("metainstanceid__c", dataValue("*meta-instance-id*"))
 ))
),

beta.each(
  merge(dataPath("data[*].attendee_new[*]"), fields(
      field("parentId", lastReferenceValue("id"))
    )),
  create("ODK_Child_2__c", fields(
    field("ODK__c", dataValue("parentId")),
    field("Barcode__c", dataValue("new_attendee_id")),
    field("First_Name__c", dataValue("new_attendee_first_name")),
    field("Last_Name__c", dataValue("new_attendee_last_name")),
    field("Phone_Number__c", dataValue("new_attendee_phone"))
  ))
),

beta.each(
  merge(dataPath("data[*].attendee[*]"), fields(
    field("parentId", function(state){return state.references[state.references.length-1].id}) //gets the sfID of the 1st item created
  )),
  create("ODK_Child_1__c", fields(
    field("ODK__c", dataValue("parentId")),
    field("Barcode__c", dataValue("attendee_id")),
    field("Late__c", dataValue("late"))
  ))
)
```

**Comment by taylordowns2000** [comment] 2016-05-05 12:23
@Natalieflp , @ryanwongsa , @aleksagk , @odavies , @ktmccl , thanks for your patience here.

@stuartc did a full review of this issue and identified the cause as a breaking change in [version 1.6](https://github.com/jsforce/jsforce/releases/tag/1.6.0) of the external Salesforce javascript client we use to load data into Salesforce. We've now locked our client to version 1.5.1 and `combine` is working as expected (and throwing errors properly) again.

More importantly, we are locking down all of the dependencies related to job running so that updates to external software (with potentially breaking changes) will not be incorporated into OpenFn. We are also in the process of developing an internal "build system" which, in effect, freezes all of the code related to a specific job so that even changes to OpenFn, introduced by our team, would not have any effect on previously written jobs. Users could, of course, make changes to their jobs and incorporate new versions of helper functions, language-packs, etc., but if a particular job is set, you can count on it running the way you tested it unless *you* choose to upgrade it.

We're well aware that our reputation depends on predictability, and we're taking every measure we can to ensure that if a job works today, it will work tomorrow. While it's still possible that a new version of Salesforce could introduce breaking changes to your existing jobs, the chances of that happening without fair warning are very slim because they have a track record of solid documentation around all changes to their APIs.

Since the Salesforce client is now locked and working with `combine` we will **not be deprecating** that helper function or dissuading users from writing expressions with it. I've updated the wiki referencing combine [here](https://github.com/OpenFn/core-docs/wiki/4.-Jobs#odk-to-sf-create-parent-and-many-children-with-parent-data) and am closing this issue.

Thanks for your help in finding and resolving this bug!

Taylor

**Closed by taylordowns2000** 2016-05-05 12:23 UTC
Labels: job writing
