### ISSUE TITLE
Job status colouring is not intuitive

### ISSUE THREAD

**Issue by carlhughes** [OpenFn/core-docs#20] opened 2016-02-25 12:13 UTC
- Failed jobs are blue
- Successful jobs are red

I think it should be the other way around.

![openfn successful jobs](https://cloud.githubusercontent.com/assets/11273278/13319369/3594be7c-dbe7-11e5-883e-6ea2bee2fe6e.png)

**Comment by taylordowns2000** [comment] 2016-02-25 12:46
Hi @carlhughes , thanks for flagging this. As best I can tell, blue is reserved for `pending` jobs, while red is for `failed` and green is for `success`. Click into one of those receipts and "retry" the job to force a process... this is necessary if auto-process isn't turned on. You should then see it as green, red, or blue after refreshing your page. I'll leave the issue open until we confirm that this is the cause.

**Comment by taylordowns2000** [comment] 2016-02-25 13:21
Closing this issue, but opening a new one around the testing/reprocessing flow of work. It's not intuitive, at the moment, and we're building a better user flow there. Thank you, @carlhughes . See #21 .

**Closed by taylordowns2000** 2016-02-25 13:21 UTC
